language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "11"
    - "10"

services: mongodb

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
